# docker-compose for running WOC locally

services:
  pg:
    image: "postgres:alpine"
    container_name: "woc-postgres"
    env_file:
      - ".env.development"
    ports:
      - "3999:3999"
    volumes:
      - "pg:/var/lib/postgresql/data"
    restart: "always"

volumes:
  pg: null
