name: Check that 'next export' works
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  next-export:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - uses: actions/cache@v2
      with:
        path: |
          ~/.npm
          ${{ github.workspace }}/.next/cache
        # Generate a new cache whenever packages or source files change.
        key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
        # If source files changed but packages didn't, rebuild from a prior cache.
        restore-keys: |
          ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-
    - uses: actions/setup-node@v2
      with:
        node-version: '16.x' # Same as in package.json
    - name: Use .env.development
      run: ln -s .env.development .env
    - name: Install dependencies
      run: npm ci
    - name: Build the app
      run: npm run build
    - name: Run 'next export'
      run: npx next export
