name: Playwright tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: ${{ matrix.browser }}
    timeout-minutes: 60
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        browser: [chromium, firefox, webkit]

    services:
      postgres:
        image: postgres:latest
        # Same as in .env.dev
        env:
          POSTGRES_PASSWORD: password
          POSTGRES_USER: user
          POSTGRES_DB: db_dev
        ports:
          - 3999:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - uses: actions/setup-node@v2
      with:
        node-version: '16.x' # Same as in package.json
    - name: Use .env.dev
      run: ln -s .env.dev .env
    - name: Install dependencies
      run: npm ci
    - name: Create DB tables
      run: |
        echo 'CREATE EXTENSION IF NOT EXISTS "uuid-ossp";' | npx prisma db execute --preview-feature --schema=prisma/schema.prisma --stdin
        npx prisma db push
    # Note: we always install Chromium because we use it in playwright-setup.ts, but ideally it should be fixed
    - name: Install Playwright
      run: npx playwright install --with-deps ${{ matrix.browser }} chromium
    - name: Build the app
      run: npm run build
    # Note: Playwright will start the server by itself, see playwright.config.ts
    - name: Run Playwright tests
      run: npx playwright test --browser ${{ matrix.browser }}
    - uses: actions/upload-artifact@v2
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
