name: Playwright tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        # Same as in .env.dev
        env:
          POSTGRES_PASSWORD: password
          POSTGRES_USER: user
          POSTGRES_DB: db_dev
        ports:
          - 3999:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - uses: actions/setup-node@v2
      with:
        node-version: '16.x' # Same as in package.json
    - name: Use .env.dev
      run: ln -s .env.dev .env
    - name: Install dependencies
      run: npm ci
    - name: Create DB tables
      run: npx prisma db push
    - name: Install Playwright
      run: npx playwright install --with-deps
    - name: Build the app
      run: npm run build
    # Note: Playwright will start the server by itself, see playwright.config.ts
    - name: Run Playwright tests
      run: npx playwright test
    - uses: actions/upload-artifact@v2
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
